### ISSUE TITLE
Where is json and how to download data?

### ISSUE THREAD

**Issue by CHR-ray** [VITA-Group/Shake-to-Leak#1]
### System Info

Traceback (most recent call last):
  File "sp_gen.py", line 18, in <module>
    names=json.load(open('data/priv_domains.json','r'))
FileNotFoundError: [Errno 2] No such file or directory: 'data/priv_domains.json'

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

python sp_gen.py

### Expected behavior

run correctly

**Comment by zoharli** [comment]
Json data has been uploaded.

Unfortunately, we are unable to provide resources of LAION-2b data. Please ask LAION authors for dataset request.
As a workaround, we recommend you to check the [LAION-400M dataset](https://www.kaggle.com/datasets/romainbeaumont/laion400m), which should be a subset of the LAION-2b dataset and thus a subset of the stable diffusion model pre-training set.
